langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-96e3056b5ebf423a8c2db058b2fce751
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      response-format: json_object
      strict-json-schema: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-96e3056b5ebf423a8c2db058b2fce751
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
